#!/usr/bin/env node
/**
 * Builds the library stylesheet from its area files.
 *
 * The source of the stylesheet is `src/styles/NN-area.css`; this script concatenates those files,
 * byte for byte, in file-name order into `src/index.css`, which is committed (tests, demos and the
 * build read it by path) and published as `dist/styles.css`. Order is the cascade: a later file
 * wins ties with an earlier one, so a file's number says where its rules sit, and a rule moves to
 * another file only together with that consequence in mind.
 *
 *   node scripts/build-css.mjs           write src/index.css
 *   node scripts/build-css.mjs --check   exit 1 if src/index.css is not what the area files give
 *   node scripts/build-css.mjs --watch   rewrite it whenever an area file changes
 */
import { readFileSync, writeFileSync, readdirSync, watch } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PARTS = join(ROOT, 'src', 'styles');
const OUT = join(ROOT, 'src', 'index.css');

export const HEADER = '/* Generated by scripts/build-css.mjs from src/styles/*.css — edit those files, not this one. */\n';

/** The area files, in the order they are concatenated. */
export const areaFiles = () => readdirSync(PARTS).filter(f => f.endsWith('.css')).sort();

/** The stylesheet the area files give. */
export const buildCss = () => HEADER + areaFiles().map(f => readFileSync(join(PARTS, f), 'utf8')).join('');

const write = () => { writeFileSync(OUT, buildCss()); console.log(`src/index.css written from ${areaFiles().length} area files`); };

if (import.meta.url === `file://${process.argv[1]}`) {
  const arg = process.argv[2];
  if (arg === '--check') {
    if (readFileSync(OUT, 'utf8') !== buildCss()) {
      console.error('src/index.css is out of date: edit src/styles/*.css, then run `npm run css`.');
      process.exit(1);
    }
    console.log('src/index.css is up to date');
  } else if (arg === '--watch') {
    write();
    watch(PARTS, () => { try { write(); } catch (e) { console.error(e.message); } });
  } else {
    write();
  }
}
